version: '2'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  travelcheck:
    image: "travelcheck"
    restart: always
    links:
      - mongo
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    volumes:
      - "/etc/letsencrypt/archive/escapefromberl.in:/etc/letsencrypt/archive/escapefromberl.in"
      - "/etc/letsencrypt/live/escapefromberl.in:/etc/letsencrypt/live/escapefromberl.in"
